# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luo/Linux-C-Web-Server_Copy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luo/Linux-C-Web-Server_Copy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luo/Linux-C-Web-Server_Copy/CMakeFiles /home/luo/Linux-C-Web-Server_Copy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luo/Linux-C-Web-Server_Copy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Linux_C_Web_Server

# Build rule for target.
Linux_C_Web_Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Linux_C_Web_Server
.PHONY : Linux_C_Web_Server

# fast build rule for target.
Linux_C_Web_Server/fast:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/build
.PHONY : Linux_C_Web_Server/fast

daemon_init.o: daemon_init.cpp.o

.PHONY : daemon_init.o

# target to build an object file
daemon_init.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/daemon_init.cpp.o
.PHONY : daemon_init.cpp.o

daemon_init.i: daemon_init.cpp.i

.PHONY : daemon_init.i

# target to preprocess a source file
daemon_init.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/daemon_init.cpp.i
.PHONY : daemon_init.cpp.i

daemon_init.s: daemon_init.cpp.s

.PHONY : daemon_init.s

# target to generate assembly for a file
daemon_init.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/daemon_init.cpp.s
.PHONY : daemon_init.cpp.s

log.o: log.cpp.o

.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i

.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s

.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/main.cpp.s
.PHONY : main.cpp.s

parse_config.o: parse_config.cpp.o

.PHONY : parse_config.o

# target to build an object file
parse_config.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/parse_config.cpp.o
.PHONY : parse_config.cpp.o

parse_config.i: parse_config.cpp.i

.PHONY : parse_config.i

# target to preprocess a source file
parse_config.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/parse_config.cpp.i
.PHONY : parse_config.cpp.i

parse_config.s: parse_config.cpp.s

.PHONY : parse_config.s

# target to generate assembly for a file
parse_config.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/parse_config.cpp.s
.PHONY : parse_config.cpp.s

parse_option.o: parse_option.cpp.o

.PHONY : parse_option.o

# target to build an object file
parse_option.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/parse_option.cpp.o
.PHONY : parse_option.cpp.o

parse_option.i: parse_option.cpp.i

.PHONY : parse_option.i

# target to preprocess a source file
parse_option.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/parse_option.cpp.i
.PHONY : parse_option.cpp.i

parse_option.s: parse_option.cpp.s

.PHONY : parse_option.s

# target to generate assembly for a file
parse_option.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/parse_option.cpp.s
.PHONY : parse_option.cpp.s

processpool/processhttp.o: processpool/processhttp.cpp.o

.PHONY : processpool/processhttp.o

# target to build an object file
processpool/processhttp.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/processpool/processhttp.cpp.o
.PHONY : processpool/processhttp.cpp.o

processpool/processhttp.i: processpool/processhttp.cpp.i

.PHONY : processpool/processhttp.i

# target to preprocess a source file
processpool/processhttp.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/processpool/processhttp.cpp.i
.PHONY : processpool/processhttp.cpp.i

processpool/processhttp.s: processpool/processhttp.cpp.s

.PHONY : processpool/processhttp.s

# target to generate assembly for a file
processpool/processhttp.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/processpool/processhttp.cpp.s
.PHONY : processpool/processhttp.cpp.s

protocal.o: protocal.cpp.o

.PHONY : protocal.o

# target to build an object file
protocal.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/protocal.cpp.o
.PHONY : protocal.cpp.o

protocal.i: protocal.cpp.i

.PHONY : protocal.i

# target to preprocess a source file
protocal.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/protocal.cpp.i
.PHONY : protocal.cpp.i

protocal.s: protocal.cpp.s

.PHONY : protocal.s

# target to generate assembly for a file
protocal.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/protocal.cpp.s
.PHONY : protocal.cpp.s

secure_access.o: secure_access.cpp.o

.PHONY : secure_access.o

# target to build an object file
secure_access.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/secure_access.cpp.o
.PHONY : secure_access.cpp.o

secure_access.i: secure_access.cpp.i

.PHONY : secure_access.i

# target to preprocess a source file
secure_access.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/secure_access.cpp.i
.PHONY : secure_access.cpp.i

secure_access.s: secure_access.cpp.s

.PHONY : secure_access.s

# target to generate assembly for a file
secure_access.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/secure_access.cpp.s
.PHONY : secure_access.cpp.s

wrap.o: wrap.cpp.o

.PHONY : wrap.o

# target to build an object file
wrap.cpp.o:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/wrap.cpp.o
.PHONY : wrap.cpp.o

wrap.i: wrap.cpp.i

.PHONY : wrap.i

# target to preprocess a source file
wrap.cpp.i:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/wrap.cpp.i
.PHONY : wrap.cpp.i

wrap.s: wrap.cpp.s

.PHONY : wrap.s

# target to generate assembly for a file
wrap.cpp.s:
	$(MAKE) -f CMakeFiles/Linux_C_Web_Server.dir/build.make CMakeFiles/Linux_C_Web_Server.dir/wrap.cpp.s
.PHONY : wrap.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Linux_C_Web_Server"
	@echo "... daemon_init.o"
	@echo "... daemon_init.i"
	@echo "... daemon_init.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parse_config.o"
	@echo "... parse_config.i"
	@echo "... parse_config.s"
	@echo "... parse_option.o"
	@echo "... parse_option.i"
	@echo "... parse_option.s"
	@echo "... processpool/processhttp.o"
	@echo "... processpool/processhttp.i"
	@echo "... processpool/processhttp.s"
	@echo "... protocal.o"
	@echo "... protocal.i"
	@echo "... protocal.s"
	@echo "... secure_access.o"
	@echo "... secure_access.i"
	@echo "... secure_access.s"
	@echo "... wrap.o"
	@echo "... wrap.i"
	@echo "... wrap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

